Update `evalexpr`, use default branch for our `resistor-calc` fork
racklet/electronics-prototyping pull request #23
Opened 2021-07-21 11:01 UTC by twelho

Thanks to [ISibboI](https://github.com/ISibboI) for getting an `evalexpr` release with https://github.com/ISibboI/evalexpr/pull/87 out so quickly! Update the evaluator to use it right away, and also switch to the default branch for our `resistor-calc` fork.

2021-07-22 11:57 UTC, chiplet requested changes
Build fails for me with the following errors:
```shell
user@v902-81 ➜  kicad_rs git:(import-updates) ✗ cargo build
    Updating git repository `https://github.com/racklet/kicad-parse-gen`
warning: fetching `master` branch from `https://github.com/racklet/kicad-parse-gen` but the `HEAD` reference for this repository is not the `master` branch. This behavior will change in Cargo in the future and your build may break, so it's recommended to place `branch = "master"` in Cargo.toml when depending on this git repository to ensure that your build will continue to work.
    Updating git repository `https://github.com/racklet/resistor-calc.git`
warning: fetching `master` branch from `https://github.com/racklet/resistor-calc.git` but the `HEAD` reference for this repository is not the `master` branch. This behavior will change in Cargo in the future and your build may break, so it's recommended to place `branch = "master"` in Cargo.toml when depending on this git repository to ensure that your build will continue to work.
   Compiling ppv-lite86 v0.2.10
   Compiling remove_dir_all v0.5.3
   Compiling getrandom v0.2.3
   Compiling kicad_parse_gen v7.0.2 (https://github.com/racklet/kicad-parse-gen#81d58e0d)
   Compiling resistor-calc v0.1.0 (https://github.com/racklet/resistor-calc.git#9dd4c8e8)
error[E0433]: failed to resolve: use of undeclared type `ROpBuilder`
   --> /Users/user/.cargo/git/checkouts/resistor-calc-6e3a7c70cdabcd12/9dd4c8e/src/lib.rs:127:12
    |
127 |     r.calc(ROpBuilder::new().bound("R1 + R2 ~ 500").finish())
    |            ^^^^^^^^^^ use of undeclared type `ROpBuilder`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `resistor-calc`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Looks like cargo defaults to pulling the master branch even if the default branch is switched to `fix-no-expr_builder-compile` in GitHub.

2021-07-22 12:45 UTC, twelho commented
> Build fails for me with the following errors:
> 
> ```shell
> user@v902-81 ➜  kicad_rs git:(import-updates) ✗ cargo build
>     Updating git repository `https://github.com/racklet/kicad-parse-gen`
> warning: fetching `master` branch from `https://github.com/racklet/kicad-parse-gen` but the `HEAD` reference for this repository is not the `master` branch. This behavior will change in Cargo in the future and your build may break, so it's recommended to place `branch = "master"` in Cargo.toml when depending on this git repository to ensure that your build will continue to work.
>     Updating git repository `https://github.com/racklet/resistor-calc.git`
> warning: fetching `master` branch from `https://github.com/racklet/resistor-calc.git` but the `HEAD` reference for this repository is not the `master` branch. This behavior will change in Cargo in the future and your build may break, so it's recommended to place `branch = "master"` in Cargo.toml when depending on this git repository to ensure that your build will continue to work.
>    Compiling ppv-lite86 v0.2.10
>    Compiling remove_dir_all v0.5.3
>    Compiling getrandom v0.2.3
>    Compiling kicad_parse_gen v7.0.2 (https://github.com/racklet/kicad-parse-gen#81d58e0d)
>    Compiling resistor-calc v0.1.0 (https://github.com/racklet/resistor-calc.git#9dd4c8e8)
> error[E0433]: failed to resolve: use of undeclared type `ROpBuilder`
>    --> /Users/user/.cargo/git/checkouts/resistor-calc-6e3a7c70cdabcd12/9dd4c8e/src/lib.rs:127:12
>     |
> 127 |     r.calc(ROpBuilder::new().bound("R1 + R2 ~ 500").finish())
>     |            ^^^^^^^^^^ use of undeclared type `ROpBuilder`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0433`.
> error: could not compile `resistor-calc`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ```
> 
> Looks like cargo defaults to pulling the master branch even if the default branch is switched to `fix-no-expr_builder-compile` in GitHub.

I don't get those warnings with `cargo 1.53.0 (4369396ce 2021-04-27)`, the behavior has already been changed. Are you running an outdated version of Cargo by chance?

2021-07-23 08:04 UTC, chiplet commented
Works for me as well after updating cargo to latest version and trying to build on a fresh clone.

2021-07-23 08:05 UTC, chiplet approved these changes

2021-07-23 08:05 UTC, merged